### ISSUE TITLE
Comandos semelhantes

### ISSUE THREAD

**Issue by lukelima** [perifacode/bot-perifacode#12]
Vi que alguns comandos que não acessam a APIs são bastante semelhantes e partes do código se repetem. Pq não criar uma classe que estende de MessageEmbed na qual já tenha uma string para color e um objeto para o footer ? Assim, apenas o título e a descrição seriam dinâmicos através do construtor e quebraria a repetição de ".setFooter()" e ".setColor()"

**Comment by gitlherme** [comment]
Então mano, talvez essa configuração não faça tanto sentido na questão de manutenção futuramente, fazer uma abstração da abstração pode acarretar em problemas futuros e tal.

Mas valeu pela contribuição, mano <3
