### ISSUE TITLE
Sugestão salvar data de aniversário e mensagem de parabéns. 

### ISSUE THREAD

**Issue by dev-sergio** [perifacode/bot-perifacode#25]
A ideia que quero sugerir é a seguinte, fazer com que os membros possam dar um comando para que o bot do Perifa salve em seu banco de dados, e assim quando chegar a data de aniversario da pessoa, ele mande uma mensagem fofa parabenizando-a. Algo como !aniversario 05/03 
Salvando assim o argumento passado, junto com o nome da pessoa que enviou o comando.

**Comment by eberfreitas** [comment]
Boa @dev-sergio ...

Andei dando uma olhada, precisaríamos de um banco de dados pra isso. Tem o mLab nesse plano free - https://mlab.com/plans/pricing/#plan-type=sandbox

0.5Gb deve ser mais que suficiente pra gente só gravar datas de aniversário...
