### ISSUE TITLE
Inclusão do canal do github no bot de "apresente-se"

### ISSUE THREAD

**Issue by vyamashiro** [perifacode/bot-perifacode#5]
Que tal quando o pessoal se apresentar no canal "apresente-se" o bot além de dar as boas-vindas ainda sugerir conhecer o canal no github ?

**Comment by gitlherme** [comment]
@vyamashiro boa ideia... Vou trabalhar nisso <3

Se quiser tentar e abrir PR, fica a vontade

**Comment by vyamashiro** [comment]
Eu estava pensando aqui e acho que tem uma solução um pouco mais fácil para esse caso. Que tal criar um canal chamado "início" com uma breve descrição sobre a PerifaCode e informando sobre o site e github ? Acho que seria mais fácil de encontrar e poderia até ter umas instruções sobre outros canais importante do discord (ex.: evento e desabafo), vou colocar o exemplo do canal da Shawee (Hackathons) para ficar mais claro

![Shawee](https://user-images.githubusercontent.com/15017935/77800132-e634b880-7054-11ea-9676-5fe3bb222689.PNG)

**Comment by gitlherme** [comment]
É uma boa! O que está acontecendo no momento é que eu envio uma mensagem privada, através do mee6, redirecionando pro https://github.com/perifacode/boas-vindas

**Comment by vyamashiro** [comment]
Ahh show! Legal, eu não me lembrava disso.

**Comment by gitlherme** [comment]
Fala mano, decidi dar uma melhorada nessa ideia que você passou <3

![image](https://user-images.githubusercontent.com/37789845/77984201-43e03380-72e7-11ea-80b3-717a28710277.png)

Agora quando a pessoa entra no servidor, o bot avisa ela <3

**Comment by vyamashiro** [comment]
Show de bola!
