### ISSUE TITLE
Arquivo CONTRIBUTING.md

### ISSUE THREAD

**Issue by erickm93** [perifacode/bot-perifacode#8]
Acho que seria uma boa colocar aqui um CONTRIBUTING.md para direcionar pessoas a respeito de como podem contribuir para o projeto.

Vou deixar aqui alguns exemplos que podemos seguir:

https://github.com/facebook/react/blob/master/CONTRIBUTING.md

https://github.com/rails/rails/blob/master/CONTRIBUTING.md

https://github.com/encode/django-rest-framework/blob/master/CONTRIBUTING.md

Pra uma primeira versão acredito que não seja necessário ser algo tão elaborado assim, mas um passo a passo de como contribuir já seria bem bom, o que acham?

**Comment by gitlherme** [comment]
Boa mano!

Eu tentei colocar mais ou menos isso no README, mas talvez seja legal algo um pouco mais elaborado.

Como eu nunca puxei um projeto open-source eu fiquei meio em dúvida de como fazer,

Você acha que consegue puxar uma versão inicial e fazer um PR?

**Comment by erickm93** [comment]
Nice, vou fazer uma versão de rascunho e botar lá.

A ideia é ser mais um tutorial de como fazer a contribuição, até pra ajudar quem nunca contribuiu com projeto open source e não ta acostumado com fluxo de fork e etc.

**Comment by gitlherme** [comment]
Show demais, mano!

Faz sim por favor, vou ficar no aguardo do PR 💛
